name: cnip和ads下载

on:
 #schedule:
    # 每天 UTC 00:00（北京时间 08:00）
    #- cron: '45 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare directories
        run: |
          mkdir -p mihomo-rules
          mkdir -p singbox-rules

      # =========================
      # 1. mihomo rules
      # =========================

      - name: Download mihomo cn-ip.yaml
        run: |
          curl -L \
            https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml \
            -o mihomo-rules/cn_ip.yaml

      - name: Download mihomo cn-ip.mrs
        run: |
          curl -L \
            https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs \
            -o mihomo-rules/cn_ip.mrs
            
      - name: Download mihomo cn-site.yaml
        run: |
          curl -L \
            https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml \
            -o mihomo-rules/cn_domain.yaml

      - name: Download mihomo cn-site.mrs
        run: |
          curl -L \
            https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs \
            -o mihomo-rules/cn_domain.mrs

      - name: Download mihomo ads.yaml
        run: |
          curl -L \
            https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockmihomo.yaml \
            -o mihomo-rules/ads_domain.yaml

      - name: Download mihomo ads.mrs
        run: |
          curl -L \
            https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockmihomo.mrs \
            -o mihomo-rules/ads_domain.mrs

      - name: Download mihomo ads-lite.yaml
        run: |
          curl -L \
            https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.yaml \
            -o mihomo-rules/ads_domain-lite.yaml

      - name: Download mihomo ads-lite.mrs
        run: |
          curl -L \
            https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.mrs \
            -o mihomo-rules/ads_domain-lite.mrs

      # =========================
      # 2. singbox rules
      # =========================

      - name: Download singbox cn.json
        run: |
          curl -L \
            https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geoip/cn.json \
            -o singbox-rules/cn_ip.json

      - name: Download singbox cn.srs
        run: |
          curl -L \
            https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geoip/cn.srs \
            -o singbox-rules/cn_ip.srs
            
      - name: Download singbox cn-domain.json
        run: |
          curl -L \
            https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/cn.json \
            -o singbox-rules/cn_domain.json

      - name: Download singbox cn-domain.srs
        run: |
          curl -L \
            https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/cn.srs \
            -o singbox-rules/cn_domain.srs

      - name: Download singbox ads-lite.json
        run: |
          curl -L \
            https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/category-ads-all.json \
            -o singbox-rules/ads_domain-lite.json

      - name: Download singbox ads-lite.srs
        run: |
          curl -L \
            https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/category-ads-all.srs \
            -o singbox-rules/ads_domain-lite.srs

      - name: Download singbox ads.json
        run: |
          curl -L \
            https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblocksingbox.json \
            -o singbox-rules/ads_domain.json

      - name: Download singbox ads.srs
        run: |
          curl -L \
            https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblocksingbox.srs \
            -o singbox-rules/ads_domain.srs


      # =========================
      # 3. Commit
      # =========================

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add \
            mihomo-rules/* \
            singbox-rules/*

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update CN IP & Ads rules (mihomo & singbox)"
            git push
          fi
